blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation & Help
    url: https://github.com/RAHB-REALTORS-Association/3cx-reports/blob/main/README.md
    about: Check the README for setup instructions and usage guide
  - name: 💬 Questions & Discussions
    url: https://github.com/RAHB-REALTORS-Association/3cx-reports/discussions
    about: Ask questions, share ideas, or discuss the dashboard with the team
